"""GOLDEN_RULE v2 — multi-TF multi-indicator evaluator.

USER MANDATE 2026-05-10: restore the comprehensive scorer that uses ALL TFs and ALL
indicators for entry/augment decisions. The narrow 1h-DC+BB-only version that ended
up in ez_manage._golden_rule_loop is the BAD version — this is the GOOD version
that gets backtested via backtest_golden_rule_full.py before any live wiring.

Per-TF score (out of 12):
  DC breakout, BB breakout, WT alignment, Stoch alignment, MFI extreme,
  RSI alignment, ATR liquidity, MACD cross, ADX strength, HA color,
  VWAP cross (D only), rel_vol surge.

Composite across 5 TFs (3m/5m, 15m, 1h, 4h, D):
  HTF-weighted aggregate. Multi-TF agreement determines size multiplier.

NO Sharpe number is generated by this module. All numerics output to disk
must be routed through metrics_guard per CLAUDE.md NO-LIES MANDATE.
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, Tuple


@dataclass
class GRSignal:
    fire: bool
    is_long: bool
    mult: float                    # size multiplier vs base
    composite_score: float         # 0..1 aggregate quality
    tfs_aligned: int               # of 5
    indicators_aligned: int        # average across aligned TFs (0..12)
    reason: str

    @property
    def tier(self) -> str:
        if not self.fire: return "NO_FIRE"
        if self.composite_score >= 0.80: return "T4_STRONG"
        if self.composite_score >= 0.65: return "T3_GOOD"
        if self.composite_score >= 0.50: return "T2_MID"
        return "T1_WEAK"


def _sf(d: dict, k: str, default: float = 0.0) -> float:
    """safe-fetch-float for indicator dicts / numpy scalars."""
    if d is None: return default
    v = d.get(k, default)
    if v is None: return default
    try: return float(v)
    except Exception:
        try: return float(str(v).strip())
        except Exception: return default


# ───────────────────────────── per-TF scoring ─────────────────────────────────


def _tf_score(ind: dict, tf: str, is_long: bool, current_price: float, config=None) -> Tuple[int, int, list]:
    """Score (0..12) for ONE timeframe, with per-indicator labels for logging.
    Returns (raw_count, max_possible, hits_list).
    Indicators that are missing/zero-filled count toward max but not raw.
    """
    hits = []
    raw = 0
    maxp = 0

    def _gain(field: str, lo_long: float, hi_long: float, lo_short: float, hi_short: float, label: str):
        """Generic 'in band' indicator scorer. lo/hi are LONG-favorable bounds; mirror for SHORT."""
        nonlocal raw, maxp
        v = _sf(ind, f'{field}_{tf}', float('nan'))
        if v != v:  # NaN
            return
        maxp += 1
        if is_long and lo_long <= v <= hi_long:
            raw += 1; hits.append(f'{label}_{tf}')
        elif (not is_long) and lo_short <= v <= hi_short:
            raw += 1; hits.append(f'{label}_{tf}')

    def _gt(a: float, b: float, label: str):
        nonlocal raw, maxp
        maxp += 1
        if (is_long and a > b) or ((not is_long) and a < b):
            raw += 1; hits.append(f'{label}_{tf}')

    # 1. DC breakout (LONG: close > dc_high; SHORT: close < dc_low)
    dc_h = _sf(ind, f'dc_high_{tf}'); dc_l = _sf(ind, f'dc_low_{tf}')
    if dc_h > 0 and dc_l > 0 and current_price > 0:
        maxp += 1
        if is_long and current_price > dc_h:
            raw += 1; hits.append(f'DC_BO_{tf}')
        elif (not is_long) and current_price < dc_l:
            raw += 1; hits.append(f'DC_BO_{tf}')

    # 2. BB breakout
    bb_u = _sf(ind, f'bb_upper_{tf}'); bb_l = _sf(ind, f'bb_lower_{tf}')
    if bb_u > 0 and bb_l > 0 and current_price > 0:
        maxp += 1
        if is_long and current_price > bb_u:
            raw += 1; hits.append(f'BB_BO_{tf}')
        elif (not is_long) and current_price < bb_l:
            raw += 1; hits.append(f'BB_BO_{tf}')

    # 3. WT alignment (LONG: wt1 > wt2)
    wt1 = _sf(ind, f'wt1_{tf}', float('nan')); wt2 = _sf(ind, f'wt2_{tf}', float('nan'))
    if wt1 == wt1 and wt2 == wt2:
        _gt(wt1, wt2, 'WT')

    # 4. Stoch alignment (LONG: k > d)
    sk = _sf(ind, f'stoch_k_{tf}', float('nan')); sd = _sf(ind, f'stoch_d_{tf}', float('nan'))
    if sk == sk and sd == sd and sk > 0 and sd > 0:
        _gt(sk, sd, 'STOCH')

    # 5. MFI extreme (LONG buy when oversold <40; SHORT sell when overbought >60)
    mfi = _sf(ind, f'mfi_{tf}', float('nan'))
    if mfi == mfi and mfi > 0:
        maxp += 1
        if is_long and mfi < 40:
            raw += 1; hits.append(f'MFI_OS_{tf}')
        elif (not is_long) and mfi > 60:
            raw += 1; hits.append(f'MFI_OB_{tf}')

    # 6. RSI direction (LONG: rsi > 50; SHORT: rsi < 50)
    rsi = _sf(ind, f'rsi_{tf}', float('nan'))
    if rsi == rsi and rsi > 0:
        maxp += 1
        if is_long and rsi >= 50:
            raw += 1; hits.append(f'RSI_{tf}')
        elif (not is_long) and rsi <= 50:
            raw += 1; hits.append(f'RSI_{tf}')

    # 7. ATR liquidity floor (avoid dead markets — must have ATR > 0)
    atr = _sf(ind, f'atr_{tf}', float('nan'))
    if atr == atr:
        maxp += 1
        # Only require ATR > 0 — different magnitudes per asset, just need data
        if atr > 0:
            raw += 1; hits.append(f'ATR_{tf}')

    # 8. MACD cross (use macd_crossover/macd_crossunder bool fields)
    macd_xo = _sf(ind, f'macd_crossover_{tf}', 0)
    macd_xu = _sf(ind, f'macd_crossunder_{tf}', 0)
    if macd_xo or macd_xu:
        maxp += 1
        if is_long and macd_xo > 0:
            raw += 1; hits.append(f'MACD_XO_{tf}')
        elif (not is_long) and macd_xu > 0:
            raw += 1; hits.append(f'MACD_XU_{tf}')

    # 9. ADX strength (>20 = trending; both sides need this)
    adx = _sf(ind, f'adx_{tf}', float('nan'))
    if adx == adx and adx > 0:
        maxp += 1
        if adx >= 20:
            raw += 1; hits.append(f'ADX_{tf}')

    # 10. HA color (LONG: green; SHORT: red)
    ha = ind.get(f'ha_{tf}', '') if ind else ''
    if isinstance(ha, bytes):
        try: ha = ha.decode()
        except Exception: ha = str(ha)
    ha_s = str(ha).strip().lower() if ha else ''
    if ha_s in ('green', 'red', 'neutral'):
        maxp += 1
        if is_long and ha_s == 'green':
            raw += 1; hits.append(f'HA_{tf}')
        elif (not is_long) and ha_s == 'red':
            raw += 1; hits.append(f'HA_{tf}')

    # 11. VWAP cross (D only)
    if tf == 'D':
        vwap = _sf(ind, 'vwap_D', float('nan'))
        if vwap == vwap and vwap > 0 and current_price > 0:
            maxp += 1
            if is_long and current_price > vwap:
                raw += 1; hits.append('VWAP_D')
            elif (not is_long) and current_price < vwap:
                raw += 1; hits.append('VWAP_D')

    # 12. rel_vol surge — uses 'relative_volume' field
    rv = _sf(ind, f'relative_volume_{tf}', float('nan'))
    if rv == rv and rv > 0:
        maxp += 1
        if rv >= 1.25:
            raw += 1; hits.append(f'RVOL_{tf}')

    return raw, maxp, hits


# ───────────────────────────── composite ──────────────────────────────────────


def evaluate_golden_rule_full(
    indicators: dict,
    current_price: float,
    is_long: bool,
    mode: str = 'crypto',
    config=None,
) -> GRSignal:
    """Comprehensive multi-TF multi-indicator scorer.

    mode: 'crypto' uses 3m base TF, 'tradier' uses 5m base TF.

    Returns GRSignal with:
      composite_score in [0,1]
      tfs_aligned: count of TFs scoring ≥0.5 (of 5)
      mult: size multiplier (0 if NO_FIRE, else 0.5/2.0/5.0/8.0 by tier)
    """
    if not indicators or current_price is None or current_price <= 0:
        return GRSignal(False, is_long, 0.0, 0.0, 0, 0, "NO_INDICATORS")

    base_tf = '3m' if mode == 'crypto' else '5m'
    tfs = [base_tf, '15m', '1h', '4h', 'D']
    tf_weights = {base_tf: 1.0, '15m': 1.5, '1h': 2.0, '4h': 3.0, 'D': 4.0}  # HTF heavier

    tf_results = {}
    total_weighted = 0.0
    total_maxw = 0.0
    aligned_tfs = 0
    indicator_sum = 0
    tf_count = 0
    all_hits = []

    for tf in tfs:
        raw, maxp, hits = _tf_score(indicators, tf, is_long, current_price, config)
        if maxp == 0:
            continue
        tf_count += 1
        tf_score_norm = raw / maxp  # 0..1
        weight = tf_weights[tf]
        total_weighted += tf_score_norm * weight
        total_maxw += weight
        indicator_sum += raw
        if tf_score_norm >= 0.5:
            aligned_tfs += 1
        tf_results[tf] = (raw, maxp, tf_score_norm)
        all_hits.extend(hits[:3])  # cap log size

    if tf_count == 0 or total_maxw == 0:
        return GRSignal(False, is_long, 0.0, 0.0, 0, 0, "NO_TF_DATA")

    composite = total_weighted / total_maxw
    avg_indicators = indicator_sum / max(tf_count, 1)

    # Ranking gate — must be in favorable direction per clenow_score / market_sentiment_score
    clenow = _sf(indicators, 'clenow_score', 0.0)
    sentiment = _sf(indicators, 'market_sentiment_score', 0.0)
    sepa = _sf(indicators, 'sepa_score', 0.0)
    rank_dir_score = clenow + sentiment + sepa
    ranking_ok = (is_long and rank_dir_score >= 0) or ((not is_long) and rank_dir_score <= 0)
    # If all three are zero (missing data), let it pass (don't block on missing data)
    if clenow == 0 and sentiment == 0 and sepa == 0:
        ranking_ok = True

    # Fire decision: composite ≥ threshold AND ≥3 TFs aligned AND ranking_ok
    min_composite = 0.50 if config is None else float(getattr(config, 'GOLDEN_RULE_FULL_MIN_COMPOSITE', 0.50))
    min_aligned_tfs = 3 if config is None else int(getattr(config, 'GOLDEN_RULE_FULL_MIN_ALIGNED_TFS', 3))

    fire = (composite >= min_composite) and (aligned_tfs >= min_aligned_tfs) and ranking_ok

    # Size tier
    if not fire:
        mult = 0.0
    elif composite >= 0.80 and aligned_tfs >= 4:
        mult = 8.0
    elif composite >= 0.65 and aligned_tfs >= 4:
        mult = 5.0
    elif composite >= 0.55:
        mult = 2.0
    else:
        mult = 0.5

    reason = (
        f"GR2_{('L' if is_long else 'S')}_comp={composite:.2f}_tfs={aligned_tfs}/{tf_count}"
        f"_avg_ind={avg_indicators:.1f}_rank={rank_dir_score:.2f}"
        f"_hits={','.join(all_hits[:6])}"
    )

    return GRSignal(
        fire=fire, is_long=is_long, mult=mult, composite_score=composite,
        tfs_aligned=aligned_tfs, indicators_aligned=int(round(avg_indicators)),
        reason=reason,
    )


# ───────────────────────────── exit logic for backtest ────────────────────────


def evaluate_exit_full(
    entry_price: float,
    current_price: float,
    is_long: bool,
    bars_held: int,
    indicators: dict,
    mode: str = 'crypto',
    config=None,
) -> Tuple[bool, str]:
    """Exit decision for backtest. Returns (should_exit, reason).
    Live system has its own exits — this is for the BACKTEST harness only.

    Triggers:
      1. Take profit at +TP%
      2. Stop loss at -SL%
      3. Reverse signal (full GR signal flips against)
      4. Max hold bars
    """
    if entry_price <= 0 or current_price <= 0:
        return True, "INVALID_PRICE"
    gain = (current_price - entry_price) / entry_price * 100.0
    if not is_long:
        gain = -gain
    tp_pct = 1.5 if config is None else float(getattr(config, 'GR2_TP_PCT', 1.5))
    sl_pct = 0.8 if config is None else float(getattr(config, 'GR2_SL_PCT', 0.8))
    max_bars = 200 if config is None else int(getattr(config, 'GR2_MAX_BARS', 200))
    if gain >= tp_pct: return True, f"TP_{gain:.2f}%"
    if gain <= -sl_pct: return True, f"SL_{gain:.2f}%"
    if bars_held >= max_bars: return True, f"MAX_BARS_{bars_held}"
    # Reverse signal exit
    rev = evaluate_golden_rule_full(indicators, current_price, not is_long, mode=mode, config=config)
    if rev.fire and rev.composite_score >= 0.65:
        return True, f"REVERSE_GR2_comp{rev.composite_score:.2f}"
    return False, ""
