#include <math.h>
#include <stdint.h>
#include <string.h>

/*
 * Tight state scan for tools/vec_top_exit_campaign.py.
 *
 * Signals and rolling features are produced in NumPy.  This loop owns only the
 * path-dependent position/exit/re-entry state.  A signal observed at close i is
 * always filled at open i+1.  It has no dependency on live trading code.
 */

typedef struct {
    double final_equity;
    double max_drawdown_pct;
    double held_bars;
    double held_seconds;
    double saved_price_sum_pct;
    double saved_price_max_pct;
    double missed_move_sum_pct;
    double missed_move_max_pct;
    double reclaim_overshoot_sum_pct;
    double reclaim_overshoot_max_pct;
    double turnover;
    int round_trips;
    int technical_exits;
    int reentries;
    int reclaim_reentries;
    int resting_reclaim_reentries;
    int lower_reentries;
    int positive_saved_reentries;
    int flat_episodes;
    int bars_flat_beyond_reclaim;
    int rejected_exit_signals;
    int winning_exits;
    int losing_exits;
    int insolvent;
} ScanMetrics;

static double entry_fill(double px, int side, double slip) {
    /* LONG buys higher; SHORT sells lower. */
    return side > 0 ? px * (1.0 + slip) : px * (1.0 - slip);
}

static double exit_fill(double px, int side, double slip) {
    /* LONG sells lower; SHORT covers higher. */
    return side > 0 ? px * (1.0 - slip) : px * (1.0 + slip);
}

static double position_equity(
    double entry_equity,
    double entry_px,
    double current_px,
    int side
) {
    if (!(entry_px > 0.0)) return entry_equity;
    return entry_equity * (1.0 + (double)side * (current_px - entry_px) / entry_px);
}

static void update_drawdown(double equity, double *peak, double *max_dd_pct) {
    if (!isfinite(equity)) return;
    if (equity > *peak) *peak = equity;
    if (*peak > 0.0) {
        double dd = 100.0 * (*peak - equity) / *peak;
        if (dd > *max_dd_pct) *max_dd_pct = dd;
    }
}

int vec_top_exit_scan(
    int n,
    int side,
    int exit_mode,       /* 1 Chandelier; 2 event; 3 MFE lock; 4 entry-frozen stop */
    int reentry_mode,    /* 0 none; 1 E10; 2 E11+delayed E10; 3 E11; 4 E11+resting E10 */
    const int64_t *ts,
    const double *open_px,
    const double *high_px,
    const double *low_px,
    const double *close_px,
    const double *atr,
    const uint8_t *exit_event,
    const double *raw_stop,
    const double *struct_ref,
    const uint8_t *lower_event,
    double reclaim_buffer_atr,
    double lower_gap_atr,
    double min_profit_gate,
    double min_mfe_atr_gate,
    double cost_rate,
    double slip_rate,
    ScanMetrics *out
) {
    if (!out || n < 2 || (side != 1 && side != -1)) return 1;
    memset(out, 0, sizeof(*out));

    double equity = 1.0;
    double peak_equity = 1.0;
    double max_dd_pct = 0.0;
    int in_position = 1;
    int pending_exit = 0;
    int pending_entry = 0; /* 1 reclaim, 2 lower */
    double pending_ref = NAN;

    double entry_px = entry_fill(open_px[0], side, slip_rate);
    /*
     * Faithful engine cost model: the configured stock cost is a round-trip
     * charge applied once at close, against entry position value.  The CLI
     * supplies the one-way rate, hence 2*cost_rate below.  Slippage remains in
     * the entry/exit fill prices and is not part of this cash charge.
     */
    double entry_equity = equity;
    equity = entry_equity;
    out->turnover += 1.0;
    int64_t hold_start_ts = ts[0];

    double trail_stop = NAN;
    double position_extreme = entry_px;
    int mfe_lock_active = 0;
    double last_exit_px = NAN;
    double exit_atr = NAN;
    double reclaim_level = NAN;
    int gap_seen = 0;
    double flat_extreme = NAN;
    double flat_missed_pct = 0.0;

    for (int i = 0; i < n; ++i) {
        if (!(open_px[i] > 0.0) || !(close_px[i] > 0.0)) continue;

        /* Orders generated by close i-1 execute at open i. */
        if (pending_exit && in_position) {
            double fill = exit_fill(open_px[i], side, slip_rate);
            double gross = position_equity(entry_equity, entry_px, fill, side);
            equity = gross - entry_equity * (2.0 * cost_rate);
            if (equity > entry_equity) out->winning_exits += 1;
            if (equity < entry_equity) out->losing_exits += 1;
            out->turnover += 1.0;
            out->technical_exits += 1;
            out->round_trips += 1;
            out->held_seconds += (double)(ts[i] - hold_start_ts);
            in_position = 0;
            last_exit_px = fill;
            exit_atr = (atr[i - 1] > 0.0 && isfinite(atr[i - 1]))
                ? atr[i - 1] : fmax(1e-12, 0.01 * fill);
            if (side > 0) {
                reclaim_level = fmax(fill, isfinite(pending_ref) ? pending_ref : fill);
            } else {
                reclaim_level = fmin(fill, isfinite(pending_ref) ? pending_ref : fill);
            }
            gap_seen = 0;
            flat_extreme = fill;
            flat_missed_pct = 0.0;
            trail_stop = NAN;
            mfe_lock_active = 0;
            pending_exit = 0;
            pending_ref = NAN;
            update_drawdown(equity, &peak_equity, &max_dd_pct);
        }

        if (pending_entry && !in_position) {
            double fill = entry_fill(open_px[i], side, slip_rate);
            double saved = side > 0
                ? 100.0 * (last_exit_px - fill) / last_exit_px
                : 100.0 * (fill - last_exit_px) / last_exit_px;
            out->saved_price_sum_pct += saved;
            if (saved > out->saved_price_max_pct) out->saved_price_max_pct = saved;
            if (saved > 0.0) out->positive_saved_reentries += 1;
            out->missed_move_sum_pct += flat_missed_pct;
            if (flat_missed_pct > out->missed_move_max_pct) {
                out->missed_move_max_pct = flat_missed_pct;
            }
            out->flat_episodes += 1;
            out->reentries += 1;
            if (pending_entry == 1) {
                out->reclaim_reentries += 1;
                double overshoot = side > 0
                    ? 100.0 * fmax(0.0, fill - reclaim_level) / reclaim_level
                    : 100.0 * fmax(0.0, reclaim_level - fill) / reclaim_level;
                out->reclaim_overshoot_sum_pct += overshoot;
                if (overshoot > out->reclaim_overshoot_max_pct) {
                    out->reclaim_overshoot_max_pct = overshoot;
                }
            }
            if (pending_entry == 2) out->lower_reentries += 1;

            entry_px = fill;
            entry_equity = equity;
            equity = entry_equity;
            out->turnover += 1.0;
            hold_start_ts = ts[i];
            in_position = 1;
            pending_entry = 0;
            trail_stop = NAN;
            position_extreme = entry_px;
            mfe_lock_active = 0;
            update_drawdown(equity, &peak_equity, &max_dd_pct);
        }

        if (in_position) {
            out->held_bars += 1.0;
            if (side > 0) {
                if (high_px[i] > position_extreme) position_extreme = high_px[i];
            } else {
                if (low_px[i] < position_extreme) position_extreme = low_px[i];
            }
            double mark = position_equity(entry_equity, entry_px, close_px[i], side);
            update_drawdown(mark, &peak_equity, &max_dd_pct);
            if (mark <= 0.0) {
                out->insolvent = 1;
                equity = 0.0;
                in_position = 0;
                break;
            }

            int should_exit = 0;
            if (exit_mode == 1 && isfinite(raw_stop[i]) && raw_stop[i] > 0.0) {
                if (!isfinite(trail_stop)) {
                    trail_stop = raw_stop[i];
                } else if (side > 0) {
                    if (raw_stop[i] > trail_stop) trail_stop = raw_stop[i];
                } else {
                    if (raw_stop[i] < trail_stop) trail_stop = raw_stop[i];
                }
                should_exit = side > 0
                    ? close_px[i] < trail_stop
                    : close_px[i] > trail_stop;
            } else if (exit_mode == 2 && exit_event[i]) {
                int gate_active = min_profit_gate >= 0.0 || min_mfe_atr_gate >= 0.0;
                int gate_pass = !gate_active;
                if (min_profit_gate >= 0.0) {
                    double raw_leg = (double)side * (close_px[i] - entry_px) / entry_px;
                    gate_pass = gate_pass || raw_leg >= 2.0 * cost_rate + min_profit_gate;
                }
                if (
                    min_mfe_atr_gate >= 0.0
                    && isfinite(atr[i]) && atr[i] > 0.0
                ) {
                    double mfe = side > 0
                        ? position_extreme - entry_px
                        : entry_px - position_extreme;
                    gate_pass = gate_pass || mfe >= min_mfe_atr_gate * atr[i];
                }
                should_exit = gate_pass;
                if (!gate_pass) out->rejected_exit_signals += 1;
            } else if (
                exit_mode == 3
                && exit_event[i]
                && isfinite(atr[i]) && atr[i] > 0.0
                && isfinite(raw_stop[i]) && raw_stop[i] > 0.0
                && isfinite(struct_ref[i]) && struct_ref[i] > 0.0
            ) {
                /* raw_stop=q activation ATR; struct_ref=k tight ATR. */
                double mfe = side > 0
                    ? position_extreme - entry_px
                    : entry_px - position_extreme;
                if (!mfe_lock_active && mfe >= raw_stop[i] * atr[i]) {
                    mfe_lock_active = 1;
                }
                if (mfe_lock_active) {
                    double candidate_stop = side > 0
                        ? position_extreme - struct_ref[i] * atr[i]
                        : position_extreme + struct_ref[i] * atr[i];
                    if (!isfinite(trail_stop)) {
                        trail_stop = candidate_stop;
                    } else if (side > 0) {
                        if (candidate_stop > trail_stop) trail_stop = candidate_stop;
                    } else {
                        if (candidate_stop < trail_stop) trail_stop = candidate_stop;
                    }
                    should_exit = side > 0
                        ? close_px[i] < trail_stop
                        : close_px[i] > trail_stop;
                }
            } else if (
                exit_mode == 4
                && isfinite(raw_stop[i]) && raw_stop[i] > 0.0
            ) {
                /*
                 * Existing DC_LOW4_STOP semantics: freeze the indicator level
                 * when a position/re-entry becomes active; do not trail it.
                 */
                if (!isfinite(trail_stop)) trail_stop = raw_stop[i];
                should_exit = side > 0
                    ? close_px[i] <= trail_stop
                    : close_px[i] >= trail_stop;
            }
            if (should_exit && i + 1 < n) {
                pending_exit = 1;
                if (exit_mode == 3) {
                    pending_ref = position_extreme;
                } else if (isfinite(struct_ref[i]) && struct_ref[i] > 0.0) {
                    pending_ref = struct_ref[i];
                } else {
                    pending_ref = side > 0 ? high_px[i] : low_px[i];
                }
            }
        } else if (isfinite(last_exit_px) && last_exit_px > 0.0) {
            if (side > 0) {
                if (high_px[i] > flat_extreme) flat_extreme = high_px[i];
                flat_missed_pct = fmax(
                    flat_missed_pct,
                    100.0 * (flat_extreme - last_exit_px) / last_exit_px
                );
                if (close_px[i] > reclaim_level) out->bars_flat_beyond_reclaim += 1;
                if (!gap_seen && low_px[i] <= last_exit_px - lower_gap_atr * exit_atr) {
                    gap_seen = 1;
                }
            } else {
                if (low_px[i] < flat_extreme) flat_extreme = low_px[i];
                flat_missed_pct = fmax(
                    flat_missed_pct,
                    100.0 * (last_exit_px - flat_extreme) / last_exit_px
                );
                if (close_px[i] < reclaim_level) out->bars_flat_beyond_reclaim += 1;
                if (!gap_seen && high_px[i] >= last_exit_px + lower_gap_atr * exit_atr) {
                    gap_seen = 1;
                }
            }

            /*
             * Persistent stop-market reclaim.  The order has rested since the
             * exit: an adverse opening gap fills at the open; otherwise an
             * intrabar touch fills at the stored level plus adverse slippage.
             * A lower E11 order signalled on the prior close has already filled
             * in the pending-entry block above, so it retains causal priority.
             */
            if (reentry_mode == 4 && i + 1 < n) {
                int open_through = side > 0
                    ? open_px[i] >= reclaim_level
                    : open_px[i] <= reclaim_level;
                int touched = side > 0
                    ? high_px[i] >= reclaim_level
                    : low_px[i] <= reclaim_level;
                if (open_through || touched) {
                    double fill = open_through
                        ? entry_fill(open_px[i], side, slip_rate)
                        : entry_fill(reclaim_level, side, slip_rate);
                    double saved = side > 0
                        ? 100.0 * (last_exit_px - fill) / last_exit_px
                        : 100.0 * (fill - last_exit_px) / last_exit_px;
                    double overshoot = side > 0
                        ? 100.0 * fmax(0.0, fill - reclaim_level) / reclaim_level
                        : 100.0 * fmax(0.0, reclaim_level - fill) / reclaim_level;
                    out->saved_price_sum_pct += saved;
                    if (saved > out->saved_price_max_pct) {
                        out->saved_price_max_pct = saved;
                    }
                    if (saved > 0.0) out->positive_saved_reentries += 1;
                    out->missed_move_sum_pct += flat_missed_pct;
                    if (flat_missed_pct > out->missed_move_max_pct) {
                        out->missed_move_max_pct = flat_missed_pct;
                    }
                    out->flat_episodes += 1;
                    out->reentries += 1;
                    out->reclaim_reentries += 1;
                    out->resting_reclaim_reentries += 1;
                    out->reclaim_overshoot_sum_pct += overshoot;
                    if (overshoot > out->reclaim_overshoot_max_pct) {
                        out->reclaim_overshoot_max_pct = overshoot;
                    }
                    entry_px = fill;
                    entry_equity = equity;
                    out->turnover += 1.0;
                    hold_start_ts = ts[i];
                    in_position = 1;
                    trail_stop = NAN;
                    position_extreme = side > 0 ? high_px[i] : low_px[i];
                    mfe_lock_active = 0;
                    out->held_bars += 1.0;
                    double mark = position_equity(
                        entry_equity, entry_px, close_px[i], side
                    );
                    update_drawdown(mark, &peak_equity, &max_dd_pct);
                    continue;
                }
            }

            if (i + 1 < n) {
                int lower_allowed = (
                    reentry_mode == 2 || reentry_mode == 3 || reentry_mode == 4
                );
                int reclaim_allowed = (reentry_mode == 1 || reentry_mode == 2);
                if (lower_allowed && gap_seen && lower_event[i]) {
                    pending_entry = 2;
                } else if (reclaim_allowed) {
                    double threshold = reclaim_buffer_atr * exit_atr;
                    int reclaim = side > 0
                        ? close_px[i] >= reclaim_level + threshold
                        : close_px[i] <= reclaim_level - threshold;
                    if (reclaim) pending_entry = 1;
                }
            }
        }
    }

    if (in_position) {
        out->held_seconds += (double)(ts[n - 1] - hold_start_ts);
        double fill = exit_fill(close_px[n - 1], side, slip_rate);
        double gross = position_equity(entry_equity, entry_px, fill, side);
        equity = gross - entry_equity * (2.0 * cost_rate);
        out->turnover += 1.0;
        out->round_trips += 1;
        update_drawdown(equity, &peak_equity, &max_dd_pct);
    } else if (isfinite(last_exit_px)) {
        out->missed_move_sum_pct += flat_missed_pct;
        if (flat_missed_pct > out->missed_move_max_pct) {
            out->missed_move_max_pct = flat_missed_pct;
        }
        out->flat_episodes += 1;
    }

    out->final_equity = equity;
    out->max_drawdown_pct = max_dd_pct;
    return 0;
}
